In [16]:
import pandas as pd
import joblib

from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV, cross_val_score, train_test_split
from sklearn.svm import SVR

In [ ]:
CSV_FILE = 'EDA/df_standardized.csv'

df = pd.read_csv(CSV_FILE)
display(df.head())

,es_numerosa,educacion_madre,educacion_padre,tiempo_viaje,tiempo_estudio,consumo_alcohol_entre_semana,consumo_alcohol_fin_de_semana,suspensos,faltas,nota1,nota2,nota3,educacion_media,notas_media
0,0.0,1.00,0.75,0.0,1.0,0.0,0.0,0.0,0.0,0.615385,0.6,0.583333,0.875,0.62500
1,1.0,0.50,0.50,0.5,1.0,0.0,0.0,0.0,0.5,0.615385,0.6,0.666667,0.500,0.65625
2,1.0,1.00,0.50,0.5,0.5,0.0,0.0,0.0,0.9,0.384615,0.2,0.250000,0.750,0.28125
3,1.0,0.50,0.25,0.5,0.5,0.0,0.2,0.0,0.2,0.461538,0.4,0.666667,0.375,0.53125
4,0.0,0.25,0.50,0.5,0.0,0.0,0.6,0.0,0.0,0.615385,0.6,0.666667,0.375,0.65625

In [18]:
#n² 96%

df = df.drop(
    columns = [
        'educacion_padre', 'educacion_madre',
        'notas_media'
    ]
)

df

,es_numerosa,tiempo_viaje,tiempo_estudio,consumo_alcohol_entre_semana,consumo_alcohol_fin_de_semana,suspensos,faltas,nota1,nota2,nota3,educacion_media
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.615385,0.6,0.583333,0.875
1,1.0,0.5,1.0,0.0,0.0,0.0,0.5,0.615385,0.6,0.666667,0.500
2,1.0,0.5,0.5,0.0,0.0,0.0,0.9,0.384615,0.2,0.250000,0.750
3,1.0,0.5,0.5,0.0,0.2,0.0,0.2,0.461538,0.4,0.666667,0.375
4,0.0,0.5,0.0,0.0,0.6,0.0,0.0,0.615385,0.6,0.666667,0.375
...,...,...,...,...,...,...,...,...,...,...,...
299,1.0,0.0,1.0,0.0,0.0,0.0,0.4,0.538462,0.6,0.583333,0.750
300,1.0,0.5,1.0,0.0,0.0,0.0,0.6,0.769231,0.8,0.833333,1.000
301,1.0,0.5,1.0,0.5,0.2,0.0,0.4,0.615385,0.5,0.583333,0.625
302,1.0,0.5,0.5,0.0,0.0,0.0,0.0,0.000000,0.1,0.333333,0.875
303,1.0,1.0,0.5,0.5,0.6,0.0,0.2,0.307692,0.1,0.250000,0.875

In [19]:
# n² 94%

# df = df.drop(
#     columns = [
#         'educacion_padre', 'educacion_madre',
#         'nota1', 'nota2', 'es_numerosa'
#     ]
# )

# df

In [20]:
# n² 91

# df = df.drop(
#     columns = [
#         'educacion_padre', 'educacion_madre',
#         'nota1', 'nota2', 'tiempo_estudio'
#     ]
# )

# df

## Bibliotecas

In [21]:
# n² 94%

# df = df.drop(
#     columns = [
#         'educacion_padre', 'educacion_madre',
#         'nota1', 'nota2', 'es_numerosa'
#     ]
# )

# df

In [22]:
# 90%

# df = df.drop(
#     columns = [
#         'educacion_padre', 'educacion_madre',
#         'nota1', 'nota2'
#     ]
# )

# df

In [23]:
# # n² 85%

# df = df.drop(
#     columns = [
#         'educacion_media',
#         'nota1', 'nota2',
#     ]
# )

# df

In [24]:
# #n² 10%

# df = df.drop(
#     columns = [
#         'educacion_media',
#         'nota1', 'nota2', 'nota3'
#     ]
# )

# df

## Modelo notas_media
Este primer modelo se va a centrar en explorar la variable `notas_media` ya que su correlacion era mayor que las 3 notas por separado

In [25]:
# Dividir los datos en conjuntos de entrenamiento y prueba
train_df, test_df = train_test_split(
    df,
    test_size=0.3
)

X_train = train_df.drop(columns=['nota3'])
Y_train = train_df["nota3"]
X_test = test_df.drop(columns=['nota3'])
Y_test = test_df["nota3"]



# display(X_train)
# display(Y_train)
# display(X_test)
# display(X_test)

### Regresión Linear

In [26]:
lr_reg = LinearRegression()

# Validación cruzada
cv_scores = cross_val_score(
    lr_reg,
    X_train, Y_train,
    cv=5, scoring='r2')

lr_reg.fit(X_train, Y_train)
Y_pred = lr_reg.predict(X_test)

# Evaluacion
r2_lr = r2_score(Y_test, Y_pred)
mae_lr = mean_absolute_error(Y_test, Y_pred)
mse_lr = mean_squared_error(Y_test, Y_pred)

In [27]:
print(f'r2_lr = {r2_lr * 100:.2f}%')
print(f'mae_lr = {mae_lr:.3f}')
print(f'mse_lr = {mse_lr:.3f}')
print(X_train)
print(Y_pred)
print(Y_test)

r2_lr = 86.56%
mae_lr = 0.058
mse_lr = 0.005
     es_numerosa  tiempo_viaje  tiempo_estudio  consumo_alcohol_entre_semana  \
2            1.0           0.5             0.5                           0.0
60           0.0           0.0             0.5                           0.0
284          0.0           0.0             0.5                           0.0
32           0.0           0.0             0.5                           0.0
140          0.0           0.0             0.5                           0.0
..           ...           ...             ...                           ...
207          1.0           0.0             0.5                           1.0
236          0.0           1.0             0.5                           0.0
34           1.0           0.5             1.0                           0.0
251          1.0           0.0             0.5                           0.5
136          1.0           0.0             0.5                           0.0

     consumo_alcohol_fin_de_semana  suspensos  faltas     nota1  nota2  \
2                              0.0        0.0     0.9  0.384615    0.2
60                             0.4        0.0     0.0  0.461538    0.5
284                            0.4        0.0     0.0  0.307692    0.3
32                             0.0        0.0     0.4  0.769231    0.8
140                            0.0        0.0     0.0  0.307692    0.1
..                             ...        ...     ...       ...    ...
207                            0.6        0.0     0.0  0.384615    0.3
236                            0.2        0.0     0.2  0.769231    0.7
34                             0.0        0.0     1.0  0.461538    0.2
251                            0.6        0.0     1.0  0.461538    0.3
136                            0.0        0.0     0.4  0.153846    0.0

     educacion_media
2              0.750
60             0.750
284            0.625
32             0.500
140            0.500
..               ...
207            0.500
236            0.875
34             0.375
251            0.500
136            0.500

[212 rows x 10 columns]
[0.59968559 0.39015261 0.84577606 0.44073403 0.45552991 0.65461843
 0.09441407 0.5246798  0.7226658  0.85867789 0.59185006 0.47665899
 0.95934449 0.85636078 0.36911516 0.35446677 0.21841462 0.46633361
 0.72475609 0.43117065 0.43935385 0.5904515  0.60597448 0.24586031
 0.22217702 0.16858197 0.97895043 0.43327833 0.33654241 0.53972856
 0.34547422 0.28324493 0.80940889 0.47931156 0.3954352  0.20700209
 0.91735122 0.39551388 0.8622744  0.64009953 0.63797547 0.70193892
 0.46134493 0.52547759 0.18222164 0.51918037 0.48882426 0.39843961
 0.24792071 0.45999604 0.32354748 0.64616647 0.67787639 0.54089788
 0.27008214 0.12886514 0.34512265 0.73644525 0.50347629 0.58338504
 0.39903427 0.23947522 0.37772044 0.94752797 0.34206721 0.83796919
 0.44939428 0.1226199  0.2703402  0.76676384 0.29653175 0.4630788
 0.73413364 0.63661901 0.33826939 0.48942019 0.29087363 0.67926654
 0.57761311 0.64594367 0.32111779 0.64340911 0.85198527 0.40179163
 0.63095472 0.74979451 0.49034621 0.47164647 0.26770985 0.472155
 0.64812767 0.26211188]
210    0.583333
142    0.416667
271    0.833333
208    0.666667
187    0.500000
         ...
160    0.500000
234    0.333333
144    0.500000
39     0.583333
89     0.166667
Name: nota3, Length: 92, dtype: float64

In [28]:
# Crear y entrenar el modelo
model = GradientBoostingRegressor(n_estimators=100)
model.fit(X_train, Y_train)

# Predecir
Y_pred_gb = model.predict(X_test)

# Evaluación
r2_gb = r2_score(Y_test, Y_pred_gb)
mae_gb = mean_absolute_error(Y_test, Y_pred_gb)
mse_gb = mean_squared_error(Y_test, Y_pred_gb)

# Mostrar las métricas
display(r2_gb)
display(mae_gb)
display(mse_gb)

0.8584749351337325

np.float64(0.06008739325005621)

np.float64(0.0057826187302596295)

In [29]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)
ridge.fit(X_train, Y_train)

Y_pred_ridge = model.predict(X_test)

r2_ridge = r2_score(Y_test, Y_pred_ridge)
mae_ridge = mean_absolute_error(Y_test, Y_pred_ridge)
mse_ridge = mean_squared_error(Y_test, Y_pred_ridge)

display(r2_ridge)
display(mae_ridge)
display(mse_ridge)

0.8584749351337325

np.float64(0.06008739325005621)

np.float64(0.0057826187302596295)

In [30]:
from sklearn.linear_model import Lasso

model = Lasso(alpha=0.1)
model.fit(X_train, Y_train)

Y_pred_lasso = model.predict(X_test)

r2_lasso = r2_score(Y_test, Y_pred_lasso)
mae_lasso = mean_absolute_error(Y_test, Y_pred_lasso)
mse_lasso = mean_squared_error(Y_test, Y_pred_lasso)

display(r2_lasso)
display(mae_lasso)
display(mse_lasso)

-0.002446417925171751

np.float64(0.16521397320207817)

np.float64(0.04095928475887546)